version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8083"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
